apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        networks: '[
          { "name": "calico"},
          { "name": "weave"}
        ]'
    spec:
      containers:
      - name: busybox
        image: bcmt-registry:5000/busybox:latest
        command: ["top"]
        stdin: true
        tty: true
      dnsPolicy: Default
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: nginx

---

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:2
        ports:
        - containerPort: 80
          protocol: TCP
        args:
---
# ------------------- Dashboard Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31001   
  selector:
    k8s-app: nginx
